services:
  - type: web
    name: yolo-flask-app
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6