services:
  - type: web
    name: yolo-flask-app
    env: python
    plan: free
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn --log-level debug --bind 0.0.0.0:$PORT --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12